config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  post '/rate' => 'rater#create', :as => 'rate'
  resources :photos
  resources :categories
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {registrations: 'registrations'}
  root "home#index"
  resources :photos, only: :show do
    resources :comments
  end
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  resources :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :photo
  belongs_to :user
  acts_as_tree order: 'created_at DESC'
  validates :description, presence: true
  rails_admin do
    list do
      field :description do
        label 'Description'
      end
      field :photo_id do
        label 'Photo name'
        formatted_value do
          Photos.find_by(id: value).name
        end
      end
      field :email do
        label 'User'
        formatted_value do
          Users.find_by(id: value).name
        end
      end
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]

  def new
    @comment = Comment.new(parent_id: params[:parent_id])
    @comment_old = Comment.find_by(id: params[:parent_id])
    @photo = Photo.find_by(id: @comment_old.photo_id)
    @comment.photo_id = @photo.id
    respond_to do |format|
      format.html do
        redirect_to @photo
      end
      format.js
    end
  end

  def create
    if comment_params["parent_id"].nil?
      @photo = Photo.find(params[:photo_id])
      @comment = @photo.comments.build(comment_params)
    else
      @comment_old = Comment.find_by(id: comment_params["parent_id"].to_i)
      @photo = Photo.find_by(id: @comment_old.photo_id)
      @comment = @photo.comments.build(comment_params)
    end
    @comment.user_id = current_user.id
    if @comment.save
      @comments = @photo.comments.order("created_at desc").where(parent_id: nil).page(params[:page]).per(10)
      @comments_parents = @photo.comments.order("created_at desc").where(parent_id: @comment.id)
      respond_to do |format|
        format.html do
          redirect_to @photo
        end
        format.js
      end
    else
      redirect_to @photo
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @photo = @comment.photo
    if @comment.parent_id.nil?
      @comments = Comment.where(parent_id: @comment.id)
      unless @comments.nil?
        if @comments.length > 1
          @comments.each do |comment|
            comment.destroy
          end
        elsif @comments.length > 0
          @comments.destroy
        end
      end
      @comment.destroy
      @comments = @photo.comments.order("created_at desc").where(parent_id: nil).page(params[:page]).per(10)
    else
      @comments = @photo.comments.order("created_at desc").where(parent_id: nil).page(params[:page]).per(10)
      @comment_old = Comment.find_by(id: @comment.parent_id)
      @comment.destroy
      @comments_parents = @photo.comments.order("created_at desc").where(parent_id: @comment_old.id)
    end
    respond_to do |format|
      format.html do
        redirect_to @photo
      end
      format.js
    end
  end

  def edit
    @photo = @comment.photo
    respond_to do |format|
      format.html do
        redirect_to @photo
      end
      format.js
    end
  end

  def update
    @photo = @comment.photo
    if @comment.update(comment_params)
      @comments = @photo.comments.order("created_at desc").where(parent_id: nil).page(params[:page]).per(10)
      @comments_parents = @photo.comments.order("created_at desc").where(parent_id: @comment.id)
      respond_to do |format|
        format.html do
          redirect_to @photo
        end
        format.js
      end
    else
      render 'edit'
    end
  end

  private
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:user_id, :photo_id, :description, :parent_id)
  end
end

app/views/comments/_comment_form.html.erb
<%= simple_form_for [@photo, @new_comment], remote: true do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/comments/_comments.html.erb
<% if @comments.blank? %>
  <p>No comment</p>
<% else %>
  <% @comments.each do |comment| %>
    <div class="post-grids">
      <h4><% @user=comment.user %><%= @user.name%></h4>
      <p class="comments"><%= time(comment.updated_at) %></p>
      <div class="comment-<%= comment.id %>">
        <%= comment.description %>
        <div class="comment-reply-<%= comment.id %>">
          <% if user_signed_in? %>
            <% if comment.user_id == current_user.id %>
              <%= link_to 'Edit', edit_comment_path(comment.id), class: "btn btn-default", remote: true %>
              <%= link_to '', photo_comment_path(comment.photo, comment), method: :delete, data: { confirm: 'Delete comment?' }, class: 'glyphicon glyphicon-trash text-danger', id: "#{comment.id}_delete", remote: true, title: 'Delete comment', rel: 'tooltip' %>
            <% end %>
            <%= link_to 'Reply', new_comment_path(comment.id), class: "btn btn-sm btn-primary", remote: true %>
          <% end %>
        </div>
      </div>
      <div class="reply">
        <% @comments_parent = reply(comment) %>
        <% @comments_parent.each do |comment| %>
          <h4><% @user=comment.user %><%= @user.name%></h4>
          <p class="comments"><%= time(comment.updated_at) %></p>
          <div class="comment-<%= comment.id %>">
            <%= comment.description %>
            <p>
              <% if user_signed_in? %>
                <% if comment.user_id == current_user.id %>
                  <%= link_to 'Edit', edit_comment_path(comment.id), class: "btn btn-default", remote: true %>
                  <%= link_to '', photo_comment_path(comment.photo, comment), method: :delete, data: { confirm: 'Delete comment?' }, class: 'glyphicon glyphicon-trash text-danger', id: "#{comment.id}_delete", remote: true, title: 'Delete comment', rel: 'tooltip' %>
                <% end %>
              <% end %>
            </p>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/comments/_edit_comment.html.erb
<%= simple_form_for [@photo, @comment], remote: true do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
<%= link_to "Back", photo_path(@photo), remote: true, class: "btn btn-primary" %>

app/views/comments/_new_comment.html.erb
<%= simple_form_for [@photo, @comment], remote: true do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <%= f.input :parent_id, as: :hidden, input_html: { value: @comment_old.id } %>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
<%= link_to "Back", photo_path(@photo), remote: true, class: "btn btn-primary" %>

app/views/comments/create.js.erb
$('#comments-list').html('<%= j render partial: "comments/comments", object: @comments %>');
$('#comment_description').val('');

app/views/comments/destroy.js.erb
$('#comments-list').html('<%= j render partial: "comments/comments", object: @comments %>');

app/views/comments/edit.js.erb
$('.comment-<%= @comment.id %>').html('<%= j render "comments/edit_comment" %>');

app/views/comments/new.js.erb
$('.comment-reply-<%= @comment_old.id %>').html('<%= j render "comments/new_comment" %>');

app/views/comments/update.js.erb
$('#comments-list').html('<%= j render partial: "comments/comments", object: @comments %>');