config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  post '/rate' => 'rater#create', :as => 'rate'
  resources :photos
  resources :categories
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {registrations: 'registrations'}
  root "home#index"
  resources :photos, only: :show do
    resources :comments
  end
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  resources :comments
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :cate_photos, dependent: :destroy
  accepts_nested_attributes_for :cate_photos, allow_destroy: true,
    reject_if: ->(attrs) { attrs['category_id'].blank? }
  mount_uploader :image_url, ImageUrlUploader
  has_many :cate_photos
  validates :image_url, presence: true
  validates :title, presence: true
  ratyrate_rateable "price"
  rails_admin do
    list do
      field :title do
        label 'Title'
      end
      field :description do
        label 'Description'
      end
      field :image_url do
        label 'Image_url'
      end
      field :user_id do
        label 'User'
        formatted_value do
          user = User.find_by(id: value)
          user.nil? ? 'Empty' : user.name
        end
      end
    end

    edit do
      field :title do
        label 'Title'
      end
      field :description do
        label 'Description'
      end
      field :image_url do
        label 'Image_url'
      end
      field :user_id, :enum do
        label "Users"
        enum do
          User.all.map { |u| [u.name, u.id] }
        end
      end
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    if params[:q].nil?
      authenticate_user!
      @photos = Photo.all.where(user_id: current_user.id).page(params[:page]).per(5)
    else
      @photos = @search.result.page(params[:page]).per(9)
    end
  end

  def show
    @comments = @photo.comments.order("created_at desc").where(parent_id: nil).page(params[:page]).per(10)
    @new_comment = @photo.comments.new
  end

  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id
    respond_to do |format|
      if @photo.save
        format.html { redirect_to photos_url, notice: t("controllers.photos.creat_success") }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update_attributes(photo_params)
        format.html { redirect_to photos_url, notice: t("controllers.photos.update_success") }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: t("controllers.photos.destroy_success") }
      format.json { head :no_content }
    end
  end

  private
  def set_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:title, :description, :image_url,
      cate_photos_attributes: [:id, :photo_id, :category_id, :_destroy])
  end

  def set_user
    if @photo.user_id != current_user.id
      redirect_to root_path
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
  def time(time)
    distance_of_time_in_words(time, Time.now, include_seconds: true)
  end

  def reply(comment)
    @photo = comment.photo
    @photo.comments.order("created_at desc").where(parent_id: comment.id)
  end
end

app/views/photos/_cate_photo_fields.html.erb
<div class="nested-fields">
  <%= f.association :category, input_html: { style: "height: 40px" } %>
  <%= f.input :_destroy, as: :boolean %>
  <%= link_to_remove_association t("views.photos.cate_photo.remove_category"), f, class: "btn btn-danger" %>
</div>

app/views/photos/_form.html.erb
<%= simple_form_for @photo do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description, :as => :ckeditor %>
    <%= f.input :image_url, as: :file %>
    <%= f.simple_fields_for :cate_photos do |cate_photos| %>
      <%= render 'cate_photo_fields', f: cate_photos %>
    <% end %>
    <div class="links">
      <%= link_to_add_association t("views.photos.form.add_category"), f, :cate_photos, class: "btn btn-primary" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<div class= "photo">
<h1><%= t("views.photos.edit.edit_photo") %></h1>

<%= render 'form', photo: @photo %>

<%= link_to t("views.photos.edit.back"), photos_path, class: "btn btn-danger" %>
</div>

app/views/photos/index.html.erb
<% if params[:q].nil? %>
  <div class="photo">
    <p id="notice"><%= notice %></p>
    <%= link_to t("views.photos.index.new_photo"), new_photo_path, class: "btn btn-success" %>
    <br />
    <table class="table table-bordered table-photo">
      <thead>
        <tr>
          <th><%= t("views.photos.index.name") %></th>
          <th><%= t("views.photos.index.description") %></th>
          <th><%= t("views.photos.index.image") %></th>
          <th><%= t("views.photos.index.category") %></th>
          <th colspan="2"><%= t("views.photos.index.action") %></th>
        </tr>
      </thead>

      <tbody>
        <% @photos.each do |photo| %>
          <tr>
            <td><%= photo.title %></td>
            <td><%= photo.description.html_safe %></td>
            <td>
              <%= image_tag photo.image_url.url, style: "max-width: 200px; max-height: 200px" %>
            </td>
            <td>
              <% cate_photos = photo.cate_photos %>
              <% cate_photos.each do |cate_photo| %>
                <% category = cate_photo.category %>
                <%= link_to category.name, category_path(category) %>
              <% end %>
            </td>
            <td>
              <%= link_to t("views.photos.index.edit"), edit_photo_path(photo), class: "btn btn-sm btn-primary" %>
            </td>
            <td>
              <%= link_to t("views.photos.index.destroy"), photo, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-sm btn-primary" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @photos, theme: 'twitter-bootstrap-3' %>
  </div>
<% else %>
  <div class="products-catagories-area clearfix">
    <div class="amado-pro-catagory clearfix row">
      <% @photos.each do |photo| %>
        <div class="single-products-catagory clearfix">
          <a href="<%= photo_path(photo) %>">
            <%= image_tag photo.image_url.url %>
            <!-- Hover Content -->
            <div class="hover-content">
              <div class="line"></div>
              <p><%= photo.title %></p>
            </div>
          </a>
        </div>
      <% end %>
    </div>
    <%= paginate @photos, theme: 'twitter-bootstrap-3' %>
  </div>
<% end %>

app/views/photos/new.html.erb
<div class= "photo">
<h1><%= t("views.photos.new.new_photo") %></h1>

<%= render 'form', photo: @photo, class: "btn btn-danger" %>

<%= link_to t("views.photos.index.back"), photos_path, class: "btn btn-danger" %>
</div>

app/views/photos/show.html.erb
<div class="single-product-area section-padding-100 clearfix">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12 col-lg-7">
        <div class="single_product_thumb">
          <div id="product_details_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <a class="gallery_img" href="img/product-img/pro-big-1.jpg">
                  <%= image_tag @photo.image_url.url, class:"d-block w-100" %>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-5">
        <div class="single_product_desc">
          <div class="product-meta-data">
            <div class="line"></div>
            <a href="product-details.html">
              <% @cate_photos = @photo.cate_photos %>
              <% @cate_photos.each do |cate_photo| %>
                <% category = cate_photo.category %>
                <%= link_to category.name, category_path(category) %>
              <% end %>
            </a>
            <h6><%= @photo.title %></h6>
            <!-- Ratings & Review -->
            <div class="ratings-review mb-15 d-flex align-items-center justify-content-between">
              <div class="ratings">
              <% if user_signed_in? %>
                  <%= rating_for @photo, "price", disable_after_rate: true, disable_after_rate: true, half_show: false %>
                <% else %>
                  <%= rating_for @photo, "price", disable_after_rate: true, disable_after_rate: false, half_show: false  %>
                <% end %>
              </div>
            </div>
            <!-- Avaiable -->
          </div>
          <div class="short_overview my-5">
            <p><%= @photo.description.html_safe %></p>
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-5">
        <% if user_signed_in? %>
          <div id="comment_form">
            <%= render "comments/comment_form" %>
          </div>
        <% end %>
          <div id="comments-list" data-remote=true>
            <%= render partial: "comments/comments", object: @comments %>
          </div>
          <%= paginate @comments, theme: 'twitter-bootstrap-3' %>
      </div>
    </div>
  </div>
</div>

app/views/photos/show.js.erb
$('#comments-list').html('<%= j render partial: "comments/comments", object: @comments %>');