config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  post '/rate' => 'rater#create', :as => 'rate'
  resources :photos
  resources :categories
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {registrations: 'registrations'}
  root "home#index"
  resources :photos, only: :show do
    resources :comments
  end
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  resources :comments
end

app/views/layouts/_footer.html.erb
<section class="newsletter-area section-padding-100-0">
  <div class="container">
    <div class="row align-items-center">
      <!-- Newsletter Text -->
      <div class="col-12 col-lg-6 col-xl-7">
        <div class="newsletter-text mb-100">
          <h2><%= t("views.layouts.footer.subscribe") %><span><%= t("views.layouts.footer.discount") %></span></h2>
          <p><%= t("views.layouts.footer.content") %></p>
        </div>
      </div>
      <!-- Newsletter Form -->
      <div class="col-12 col-lg-6 col-xl-5">
        <div class="newsletter-form mb-100">
          <form action="#" method="post">
            <input type="email" name="email" class="nl-email" placeholder="Your E-mail">
            <input type="submit" value="Subscribe">
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- ##### Newsletter Area End ##### -->

<!-- ##### Footer Area Start ##### -->
<footer class="footer_area clearfix">
  <div class="container">
    <div class="row align-items-center">
      <!-- Single Widget Area -->
      <div class="col-12 col-lg-4">
        <div class="single_widget_area">
          <!-- Logo -->
          <div class="footer-logo mr-50">
            <a href="#"><%= image_tag("core-img/logo2.png") %></a>
          </div>
          <!-- Copywrite Text -->
          <p class="copywrite"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            <%= t("views.layouts.footer.copyright") %> &copy;<script>document.write(new Date().getFullYear());</script> <%= t("views.layouts.footer.all") %> <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="#" target="_blank"><%= t("views.layouts.footer.colorlib") %></a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          </p>
        </div>
      </div>
      <!-- Single Widget Area -->
      <div class="col-12 col-lg-8">
        <div class="single_widget_area">
          <!-- Footer Menu -->
          <div class="footer_menu">
            <nav class="navbar navbar-expand-lg justify-content-end">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#footerNavContent" aria-controls="footerNavContent" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
              <div class="collapse navbar-collapse" id="footerNavContent">
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item"><%= link_to t("views.layouts.footer.home"), root_path, class: "nav-link" %></li>
                  <% @categories.each do |category| %>
                    <li class="nav-item"><%= link_to category.name, category_path(category), class: "nav-link" %></li>
                  <% end %>
                </ul>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header-area clearfix">
  <!-- Close Icon -->
  <div class="nav-close">
    <i class="fa fa-close" aria-hidden="true"></i>
  </div>
  <!-- Logo -->
  <div class="logo">
  <%= link_to image_tag("core-img/logo.png"), "#" %>
  </div>
  <!-- Amado Nav -->
  <nav class="amado-nav">
    <ul>
      <li><%= link_to t("views.layouts.header.home"), root_path %></li>
      <% @categories.each do |category| %>
        <li><%= link_to category.name, category_path(category) %></li>
      <% end %>
      <% if user_signed_in? %>
        <li>Welcome <%= current_user.name %></li>
        <li><%= link_to t("views.layouts.header.my_photo"), photos_path %></li>
        <li><%= link_to t("views.layouts.header.edit_profile"), edit_user_registration_path %></li>
        <li><%= link_to t("views.layouts.header.logout"), destroy_user_session_path, method: :delete %></li>
        <% if current_user.role == "admin"%>
          <li><%= link_to t("views.layouts.header.admin"), rails_admin_path %></li>
        <% end %>
      <% else %>
        <li><%= link_to t("views.layouts.header.login"), new_user_session_path %></li>
        <li><%= link_to t("views.layouts.header.sign_up"), new_user_registration_path %></li>
      <% end %>
      <li>
        <%= search_form_for @search, url: photos_path, class: "form-search form-horizontal pull-right" do |f| %>
          <%= f.text_field :title_or_description_cont, class: "search-query input-large form-control" %>
          <%= f.submit t("views.layouts.header.search"), class: "btn btn-default" %>
        <% end %>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
  <body>
    <div class="main-content-wrapper d-flex clearfix">
      <div class="mobile-nav">
        <div class="amado-navbar-brand">
          <a href="#"><img src="img/core-img/logo.png" alt=""></a>
        </div>
        <div class="amado-navbar-toggler">
          <span></span><span></span><span></span>
        </div>
      </div>
      <%= render "layouts/header" %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>